# Generated by Django 3.1.3 on 2022-06-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etlapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=300)),
                ('Location', models.CharField(max_length=300)),
                ('Price', models.CharField(max_length=300)),
                ('Caracteristiques', models.CharField(max_length=500)),
                ('Pieces', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('Pictures', models.CharField(max_length=500)),
                ('Telephone', models.CharField(max_length=300)),
                ('Surface', models.CharField(max_length=300)),
            ],
        ),
    ]
